"""State management system - Redux-like architecture with hooks."""

from .store import (
    Store,
    Action,
    ActionType,
    Reducer,
    Middleware,
    Selector,
    create_store,
    combine_reducers,
    CombineReducers,
)

from .actions import (
    # Action types
    UIActionType,
    SessionActionType,
    PermissionActionType,
    WorkspaceActionType,
    NotificationType,
    # UI actions
    show_panel,
    hide_panel,
    update_panel_state,
    set_active_tab,
    set_theme,
    set_loading,
    show_notification,
    set_sidebar_collapsed,
    # Session actions
    start_session,
    end_session,
    update_session_config,
    set_current_user,
    add_tool,
    remove_tool,
    # Permission actions
    grant_permission,
    revoke_permission,
    audit_event,
    assign_role,
    # Workspace actions
    load_config,
    update_config,
    add_file,
    delete_file,
    update_file,
    set_current_project,
)

from .reducers import (
    # State dataclasses
    UIState,
    Session,
    PermissionState,
    WorkspaceState,
    # Reducers
    ui_reducer,
    session_reducer,
    permission_reducer,
    workspace_reducer,
    root_reducer,
)

from .middleware import (
    logger_middleware,
    validation_middleware,
    persistence_middleware,
    effects_middleware,
    undo_redo_middleware,
    DevToolsMiddleware,
    MetricsMiddleware,
    create_middleware_chain,
)

from .selectors import (
    # UI selectors
    select_visible_panels,
    select_panel_state,
    select_active_tab,
    select_theme,
    select_loading_state,
    select_notifications,
    select_sidebar_collapsed,
    # Session selectors
    select_current_user,
    select_current_username,
    select_current_role,
    select_session_id,
    select_available_tools,
    select_session_config,
    select_is_authenticated,
    # Permission selectors
    select_user_role,
    select_user_permissions,
    select_has_permission,
    select_audit_log,
    select_user_actions,
    select_permission_stats,
    # Workspace selectors
    select_workspace_config,
    select_workspace_files,
    select_file_content,
    select_current_project,
    select_workspace_summary,
    # Combined selectors
    select_app_state,
    SelectorCache,
    create_memoized_selector,
)

from .hooks import (
    # Setup
    setup_store,
    get_store,
    # Hooks
    use_state,
    use_effect,
    use_selector,
    use_dispatch,
    use_callback,
    use_memo,
    use_reducer,
    create_context,
    use_context,
    set_context,
    clear_all_hooks,
)

__all__ = [
    # Store
    "Store",
    "Action",
    "ActionType",
    "Reducer",
    "Middleware",
    "Selector",
    "create_store",
    "combine_reducers",
    "CombineReducers",
    # Action types
    "UIActionType",
    "SessionActionType",
    "PermissionActionType",
    "WorkspaceActionType",
    "NotificationType",
    # Actions
    "show_panel",
    "hide_panel",
    "update_panel_state",
    "set_active_tab",
    "set_theme",
    "set_loading",
    "show_notification",
    "set_sidebar_collapsed",
    "start_session",
    "end_session",
    "update_session_config",
    "set_current_user",
    "add_tool",
    "remove_tool",
    "grant_permission",
    "revoke_permission",
    "audit_event",
    "assign_role",
    "load_config",
    "update_config",
    "add_file",
    "delete_file",
    "update_file",
    "set_current_project",
    # States
    "UIState",
    "Session",
    "PermissionState",
    "WorkspaceState",
    # Reducers
    "ui_reducer",
    "session_reducer",
    "permission_reducer",
    "workspace_reducer",
    "root_reducer",
    # Middleware
    "logger_middleware",
    "validation_middleware",
    "persistence_middleware",
    "effects_middleware",
    "undo_redo_middleware",
    "DevToolsMiddleware",
    "MetricsMiddleware",
    "create_middleware_chain",
    # Selectors
    "select_visible_panels",
    "select_panel_state",
    "select_active_tab",
    "select_theme",
    "select_loading_state",
    "select_notifications",
    "select_sidebar_collapsed",
    "select_current_user",
    "select_current_username",
    "select_current_role",
    "select_session_id",
    "select_available_tools",
    "select_session_config",
    "select_is_authenticated",
    "select_user_role",
    "select_user_permissions",
    "select_has_permission",
    "select_audit_log",
    "select_user_actions",
    "select_permission_stats",
    "select_workspace_config",
    "select_workspace_files",
    "select_file_content",
    "select_current_project",
    "select_workspace_summary",
    "select_app_state",
    "SelectorCache",
    "create_memoized_selector",
    # Hooks
    "setup_store",
    "get_store",
    "use_state",
    "use_effect",
    "use_selector",
    "use_dispatch",
    "use_callback",
    "use_memo",
    "use_reducer",
    "create_context",
    "use_context",
    "set_context",
    "clear_all_hooks",
]
